#!/bin/sh
set -ev

# Directories.
root_dir=`pwd`
build_dir="$root_dir/_travis/build"

# Shortcuts.
git_clone="git clone --quiet --recursive"

# create locale for testing
sudo locale-gen nl_NL.UTF-8

# Create layout.
rm -rf "$build_dir"
mkdir -p "$build_dir"

# Compile
echo "--> Compiling urdfdom"
cd "$root_dir"
cmake .
make
